[package]
name = "rust-bake-codepoints"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fontdue = "0.7.2"
glob = "0.3.0"
png = "0.17.5"
resvg = "0.23.0"
ttf-parser = "0.15.2"
usvg = "0.23.0"
